### ISSUE TITLE
Provide a functional interface which doesn't pollute Map.prototype

### ISSUE THREAD

**Issue by chocolateboy** [nicolasdejong/map-object-facade#1]
This looks really useful, but I could never use it as it currently stands as it pollutes native objects (`Map` and `WeakMap`), which has long been [frowned upon in JS](http://www.nczonline.net/blog/2010/03/02/maintainable-javascript-dont-modify-objects-you-down-own/), and is disallowed by various [tools](https://eslint.org/docs/rules/no-extend-native) and policies e.g.:

> Extending the prototype of native objects like Object, Array and String is not allowed because it can cause compatibility problems with other add-ons or the browser itself.
>
> -- [Firefox Addon Policy](https://stackoverflow.com/q/36505440)

> Never modify builtin types, either by adding methods to their constructors or to their prototypes. Avoid depending on libraries that do this.
> 
> -- [Google JavaScript Style Guide](https://google.github.io/styleguide/jsguide.html#disallowed-features-modifying-builtin-objects)

> Extending builtins is the worst thing you can do if you don’t control the environment your code runs in.
> 
> -- [Breaking the Web with JavaScript](https://medium.com/@cpojer/breaking-the-web-with-javascript-48cc406ca98d)

Also, the method limits it to working with native Maps rather than working generically with other objects which implement the Map interface e.g. [Immutable.js Maps](https://facebook.github.io/immutable-js/docs/#/Map).

Have you considered providing a functional interface instead e.g.:

```javascript
import asObject from 'map-object-facade'

const map = new Map(...)
const obj = asObject(map)

obj['foo'] = 'bar'
```

If you really need the native method (e.g. for a private project), it could be enabled explicitly [e.g.](https://github.com/arturadib/shelljs#global-vs-local):

``` javascript
import 'map-object-facade/global'
```

**Comment by nicolasdejong** [comment]
Good points. While I think there are some cases where adding to the prototype is warranted, this is not one of them. I'll follow your suggestion.
